package login;

import com.itextpdf.text.Document;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.io.*;
import java.text.MessageFormat;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import org.apache.poi.hssf.usermodel.HSSFCell;
import org.apache.poi.hssf.usermodel.HSSFCellStyle;
import org.apache.poi.hssf.usermodel.HSSFRow;
import org.apache.poi.hssf.usermodel.HSSFSheet;
import org.apache.poi.hssf.usermodel.HSSFWorkbook;

public class AdminForm extends javax.swing.JFrame {

    // jdbc config
    private String jdbcDriver = "#####";
    private String jdbcLogin = "#####";
    private String jdbcPassword = "#####";

    int xx;
    int yy;

    public AdminForm() {
        initComponents();
        ShowUsersInJTable();

        setColor(jPanel_Manage);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel_Exit = new javax.swing.JLabel();
        jLabel_Iconified = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel_Manage = new javax.swing.JPanel();
        jLabel_ManageUsers = new javax.swing.JLabel();
        jPanel_Exit = new javax.swing.JPanel();
        jLabel_Close = new javax.swing.JLabel();
        jPanel_Login = new javax.swing.JPanel();
        jLabel_Login = new javax.swing.JLabel();
        jPanel_Txt = new javax.swing.JPanel();
        jLabel_Txt = new javax.swing.JLabel();
        jPanel_Xls = new javax.swing.JPanel();
        jLabel_Xls = new javax.swing.JLabel();
        jPanel_Print = new javax.swing.JPanel();
        jLabel_Print = new javax.swing.JLabel();
        jPanel_PDF = new javax.swing.JPanel();
        jLabel_PDF = new javax.swing.JLabel();
        jPanel_Email = new javax.swing.JPanel();
        jLabel_Email = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel_Edit = new javax.swing.JLabel();
        jLabel_Remove = new javax.swing.JLabel();
        jLabel_Add = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField_ID = new javax.swing.JTextField();
        jTextField_UserName = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField_Password = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jTextField_FirstName = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jTextField_LastName = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField_Email = new javax.swing.JTextField();
        jTextField_Age = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jTextField_January = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jTextField_February = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jTextField_March = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jTextField_April = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jTextField_May = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jTextField_June = new javax.swing.JTextField();
        jTextField_July = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jTextField_August = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jTextField_September = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jTextField_October = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextField_November = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        jTextField_December = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel_Refresh = new javax.swing.JLabel();
        jLabel_Search = new javax.swing.JLabel();
        jLabel_Clear = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_Users = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(850, 500));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel1.setLayout(null);

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));

        jLabel_Exit.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel_Exit.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Exit.setText("X");
        jLabel_Exit.setToolTipText("Exit");
        jLabel_Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ExitMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(810, 0, 44, 44);

        jLabel_Iconified.setFont(new java.awt.Font("Calibri", 1, 24)); // NOI18N
        jLabel_Iconified.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Iconified.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_Iconified.setText("-");
        jLabel_Iconified.setToolTipText("Minimize");
        jLabel_Iconified.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Iconified.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_IconifiedMouseClicked(evt);
            }
        });
        jPanel1.add(jLabel_Iconified);
        jLabel_Iconified.setBounds(790, 0, 20, 40);

        jLabel15.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("                            Administration Panel");
        jLabel15.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jLabel15MouseDragged(evt);
            }
        });
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel15MousePressed(evt);
            }
        });
        jPanel1.add(jLabel15);
        jLabel15.setBounds(0, 0, 850, 50);

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));

        jPanel_Manage.setBackground(new java.awt.Color(31, 174, 174));

        jLabel_ManageUsers.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel_ManageUsers.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_ManageUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/users.png"))); // NOI18N
        jLabel_ManageUsers.setText("  Manage Users");
        jLabel_ManageUsers.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_ManageUsers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ManageUsersMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ManageLayout = new javax.swing.GroupLayout(jPanel_Manage);
        jPanel_Manage.setLayout(jPanel_ManageLayout);
        jPanel_ManageLayout.setHorizontalGroup(
            jPanel_ManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ManageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_ManageUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_ManageLayout.setVerticalGroup(
            jPanel_ManageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ManageLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_ManageUsers, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel_Exit.setBackground(new java.awt.Color(31, 174, 174));

        jLabel_Close.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel_Close.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        jLabel_Close.setText("  Exit");
        jLabel_Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_CloseMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ExitLayout = new javax.swing.GroupLayout(jPanel_Exit);
        jPanel_Exit.setLayout(jPanel_ExitLayout);
        jPanel_ExitLayout.setHorizontalGroup(
            jPanel_ExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Close, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
        );
        jPanel_ExitLayout.setVerticalGroup(
            jPanel_ExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ExitLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_Close, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel_Login.setBackground(new java.awt.Color(31, 174, 174));

        jLabel_Login.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel_Login.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/login_adm.png"))); // NOI18N
        jLabel_Login.setText("  Login Form");
        jLabel_Login.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Login.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_LoginMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_LoginLayout = new javax.swing.GroupLayout(jPanel_Login);
        jPanel_Login.setLayout(jPanel_LoginLayout);
        jPanel_LoginLayout.setHorizontalGroup(
            jPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_LoginLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Login, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE))
        );
        jPanel_LoginLayout.setVerticalGroup(
            jPanel_LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_LoginLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel_Login, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel_Txt.setBackground(new java.awt.Color(31, 174, 174));

        jLabel_Txt.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel_Txt.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Txt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/txt.png"))); // NOI18N
        jLabel_Txt.setText("  Export data to TXT File");
        jLabel_Txt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Txt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_TxtMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_TxtLayout = new javax.swing.GroupLayout(jPanel_Txt);
        jPanel_Txt.setLayout(jPanel_TxtLayout);
        jPanel_TxtLayout.setHorizontalGroup(
            jPanel_TxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_TxtLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_TxtLayout.setVerticalGroup(
            jPanel_TxtLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel_Xls.setBackground(new java.awt.Color(31, 174, 174));

        jLabel_Xls.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel_Xls.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Xls.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/excel.png"))); // NOI18N
        jLabel_Xls.setText("  Export data to XLS File");
        jLabel_Xls.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Xls.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_XlsMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_XlsLayout = new javax.swing.GroupLayout(jPanel_Xls);
        jPanel_Xls.setLayout(jPanel_XlsLayout);
        jPanel_XlsLayout.setHorizontalGroup(
            jPanel_XlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_XlsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Xls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_XlsLayout.setVerticalGroup(
            jPanel_XlsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Xls, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel_Print.setBackground(new java.awt.Color(31, 174, 174));

        jLabel_Print.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel_Print.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Print.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/print.png"))); // NOI18N
        jLabel_Print.setText("  Print data");
        jLabel_Print.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Print.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_PrintMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_PrintLayout = new javax.swing.GroupLayout(jPanel_Print);
        jPanel_Print.setLayout(jPanel_PrintLayout);
        jPanel_PrintLayout.setHorizontalGroup(
            jPanel_PrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_PrintLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Print, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_PrintLayout.setVerticalGroup(
            jPanel_PrintLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Print, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel_PDF.setBackground(new java.awt.Color(31, 174, 174));

        jLabel_PDF.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel_PDF.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_PDF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pdf.png"))); // NOI18N
        jLabel_PDF.setText("  Export data to PDF File");
        jLabel_PDF.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_PDF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_PDFMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_PDFLayout = new javax.swing.GroupLayout(jPanel_PDF);
        jPanel_PDF.setLayout(jPanel_PDFLayout);
        jPanel_PDFLayout.setHorizontalGroup(
            jPanel_PDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_PDFLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_PDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_PDFLayout.setVerticalGroup(
            jPanel_PDFLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_PDF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel_Email.setBackground(new java.awt.Color(31, 174, 174));

        jLabel_Email.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel_Email.setForeground(new java.awt.Color(255, 255, 255));
        jLabel_Email.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/email.png"))); // NOI18N
        jLabel_Email.setText("  Send e-mail");
        jLabel_Email.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_EmailMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel_EmailLayout = new javax.swing.GroupLayout(jPanel_Email);
        jPanel_Email.setLayout(jPanel_EmailLayout);
        jPanel_EmailLayout.setHorizontalGroup(
            jPanel_EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_EmailLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel_Email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel_EmailLayout.setVerticalGroup(
            jPanel_EmailLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Manage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_Exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_Login, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_Txt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_Xls, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_Print, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_PDF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel_Email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jPanel_Manage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Xls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_PDF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Print, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 154, Short.MAX_VALUE)
                .addComponent(jPanel_Login, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Exit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(1, 1, 200, 500);

        jPanel4.setFocusTraversalPolicyProvider(true);

        jLabel_Edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/mod.png"))); // NOI18N
        jLabel_Edit.setToolTipText("Edit");
        jLabel_Edit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_EditMouseClicked(evt);
            }
        });

        jLabel_Remove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete.png"))); // NOI18N
        jLabel_Remove.setToolTipText("Remove");
        jLabel_Remove.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Remove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_RemoveMouseClicked(evt);
            }
        });

        jLabel_Add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/add.png"))); // NOI18N
        jLabel_Add.setToolTipText("Add");
        jLabel_Add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_AddMouseClicked(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setText("ID:");

        jTextField_ID.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextField_ID.setForeground(new java.awt.Color(51, 51, 51));
        jTextField_ID.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_ID.setToolTipText("");
        jTextField_ID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jTextField_UserName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextField_UserName.setForeground(new java.awt.Color(51, 51, 51));
        jTextField_UserName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_UserName.setToolTipText("");
        jTextField_UserName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabel17.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setText("Username:");

        jTextField_Password.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextField_Password.setForeground(new java.awt.Color(51, 51, 51));
        jTextField_Password.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Password.setToolTipText("");
        jTextField_Password.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabel18.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setText("Password:");

        jTextField_FirstName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextField_FirstName.setForeground(new java.awt.Color(51, 51, 51));
        jTextField_FirstName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_FirstName.setToolTipText("");
        jTextField_FirstName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabel19.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(51, 51, 51));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setText("First Name:");

        jTextField_LastName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextField_LastName.setForeground(new java.awt.Color(51, 51, 51));
        jTextField_LastName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_LastName.setToolTipText("");
        jTextField_LastName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabel20.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(51, 51, 51));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setText("Last Name:");

        jLabel21.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(51, 51, 51));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel21.setText("Email:");

        jTextField_Email.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextField_Email.setForeground(new java.awt.Color(51, 51, 51));
        jTextField_Email.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Email.setToolTipText("");
        jTextField_Email.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jTextField_Age.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextField_Age.setForeground(new java.awt.Color(51, 51, 51));
        jTextField_Age.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_Age.setToolTipText("");
        jTextField_Age.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabel22.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(51, 51, 51));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel22.setText("Age:");

        jTextField_January.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextField_January.setForeground(new java.awt.Color(51, 51, 51));
        jTextField_January.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_January.setToolTipText("");
        jTextField_January.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabel23.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(51, 51, 51));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel23.setText("January:");

        jLabel24.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(51, 51, 51));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel24.setText("Incomings:");

        jLabel25.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(51, 51, 51));
        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel25.setText("February:");

        jTextField_February.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextField_February.setForeground(new java.awt.Color(51, 51, 51));
        jTextField_February.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_February.setToolTipText("");
        jTextField_February.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabel26.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(51, 51, 51));
        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel26.setText("March:");

        jTextField_March.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextField_March.setForeground(new java.awt.Color(51, 51, 51));
        jTextField_March.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_March.setToolTipText("");
        jTextField_March.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabel27.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(51, 51, 51));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel27.setText("April:");

        jTextField_April.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextField_April.setForeground(new java.awt.Color(51, 51, 51));
        jTextField_April.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_April.setToolTipText("");
        jTextField_April.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabel28.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(51, 51, 51));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel28.setText("May:");

        jTextField_May.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextField_May.setForeground(new java.awt.Color(51, 51, 51));
        jTextField_May.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_May.setToolTipText("");
        jTextField_May.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabel29.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(51, 51, 51));
        jLabel29.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel29.setText("June:");

        jTextField_June.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextField_June.setForeground(new java.awt.Color(51, 51, 51));
        jTextField_June.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_June.setToolTipText("");
        jTextField_June.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jTextField_July.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextField_July.setForeground(new java.awt.Color(51, 51, 51));
        jTextField_July.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_July.setToolTipText("");
        jTextField_July.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabel30.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(51, 51, 51));
        jLabel30.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel30.setText("July:");

        jTextField_August.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextField_August.setForeground(new java.awt.Color(51, 51, 51));
        jTextField_August.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_August.setToolTipText("");
        jTextField_August.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabel31.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(51, 51, 51));
        jLabel31.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel31.setText("August:");

        jTextField_September.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextField_September.setForeground(new java.awt.Color(51, 51, 51));
        jTextField_September.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_September.setToolTipText("");
        jTextField_September.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabel32.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(51, 51, 51));
        jLabel32.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel32.setText("September:");

        jTextField_October.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextField_October.setForeground(new java.awt.Color(51, 51, 51));
        jTextField_October.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_October.setToolTipText("");
        jTextField_October.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabel33.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(51, 51, 51));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel33.setText("October:");

        jTextField_November.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextField_November.setForeground(new java.awt.Color(51, 51, 51));
        jTextField_November.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_November.setToolTipText("");
        jTextField_November.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabel34.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(51, 51, 51));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel34.setText("November:");

        jTextField_December.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextField_December.setForeground(new java.awt.Color(51, 51, 51));
        jTextField_December.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField_December.setToolTipText("");
        jTextField_December.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51)));

        jLabel35.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(51, 51, 51));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel35.setText("December:");

        jLabel_Refresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/refresh.png"))); // NOI18N
        jLabel_Refresh.setToolTipText("Refresh");
        jLabel_Refresh.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_RefreshMouseClicked(evt);
            }
        });

        jLabel_Search.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/search.png"))); // NOI18N
        jLabel_Search.setToolTipText("Search");
        jLabel_Search.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Search.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_SearchMouseClicked(evt);
            }
        });

        jLabel_Clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clear.png"))); // NOI18N
        jLabel_Clear.setToolTipText("Clear");
        jLabel_Clear.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel_Clear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel_ClearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addComponent(jTextField_January, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25)
                            .addComponent(jTextField_February, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jTextField_March, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel27)
                            .addComponent(jTextField_April, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel28)
                            .addComponent(jTextField_May, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel29)
                            .addComponent(jTextField_June, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jTextField_July, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel31)
                            .addComponent(jTextField_August, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32)
                            .addComponent(jTextField_September, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel33)
                            .addComponent(jTextField_October, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(jTextField_November, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel35)
                            .addComponent(jTextField_December, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jTextField_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(jTextField_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel19)
                                    .addComponent(jTextField_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jTextField_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel_Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jTextField_Age, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(1, 1, 1)
                                .addComponent(jTextField_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16))
                                .addGap(1, 1, 1)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTextField_UserName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(1, 1, 1)
                                .addComponent(jTextField_FirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(1, 1, 1)
                                .addComponent(jTextField_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel21)
                                .addGap(1, 1, 1)
                                .addComponent(jTextField_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel22)
                                .addGap(1, 1, 1)
                                .addComponent(jTextField_Age, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(25, 25, 25)
                        .addComponent(jLabel24))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Remove, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Edit, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel_Refresh, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(6, 6, 6)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(1, 1, 1)
                        .addComponent(jTextField_February, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(1, 1, 1)
                        .addComponent(jTextField_March, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(1, 1, 1)
                        .addComponent(jTextField_April, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel28)
                        .addGap(1, 1, 1)
                        .addComponent(jTextField_May, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel29)
                        .addGap(1, 1, 1)
                        .addComponent(jTextField_June, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel23)
                        .addGap(1, 1, 1)
                        .addComponent(jTextField_January, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel30)
                        .addGap(1, 1, 1)
                        .addComponent(jTextField_July, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(1, 1, 1)
                        .addComponent(jTextField_August, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel32)
                        .addGap(1, 1, 1)
                        .addComponent(jTextField_September, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addGap(1, 1, 1)
                        .addComponent(jTextField_October, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel34)
                        .addGap(1, 1, 1)
                        .addComponent(jTextField_November, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addGap(1, 1, 1)
                        .addComponent(jTextField_December, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(200, 50, 650, 180);

        jTable_Users.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTable_Users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Username", "Password", "First Name", "Last Name", "Email", "Age", "January salary", "February salary", "March salary", "April salary", "May salary", "June salary", "July salary", "August salary", "September salary", "October salary", "November salary", "December salary"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Users.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jTable_Users.setAutoscrolls(false);
        jTable_Users.getTableHeader().setReorderingAllowed(false);
        jTable_Users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jTable_UsersMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable_Users);
        if (jTable_Users.getColumnModel().getColumnCount() > 0) {
            jTable_Users.getColumnModel().getColumn(0).setPreferredWidth(30);
            jTable_Users.getColumnModel().getColumn(1).setPreferredWidth(100);
            jTable_Users.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable_Users.getColumnModel().getColumn(3).setPreferredWidth(100);
            jTable_Users.getColumnModel().getColumn(4).setPreferredWidth(100);
            jTable_Users.getColumnModel().getColumn(5).setPreferredWidth(130);
            jTable_Users.getColumnModel().getColumn(6).setPreferredWidth(50);
            jTable_Users.getColumnModel().getColumn(7).setPreferredWidth(100);
            jTable_Users.getColumnModel().getColumn(8).setPreferredWidth(100);
            jTable_Users.getColumnModel().getColumn(9).setPreferredWidth(100);
            jTable_Users.getColumnModel().getColumn(10).setPreferredWidth(100);
            jTable_Users.getColumnModel().getColumn(11).setPreferredWidth(100);
            jTable_Users.getColumnModel().getColumn(12).setPreferredWidth(100);
            jTable_Users.getColumnModel().getColumn(13).setPreferredWidth(100);
            jTable_Users.getColumnModel().getColumn(14).setPreferredWidth(100);
            jTable_Users.getColumnModel().getColumn(15).setPreferredWidth(100);
            jTable_Users.getColumnModel().getColumn(16).setPreferredWidth(100);
            jTable_Users.getColumnModel().getColumn(17).setPreferredWidth(100);
            jTable_Users.getColumnModel().getColumn(18).setPreferredWidth(100);
        }

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(212, 242, 630, 250);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(850, 500));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public Connection getConnection() {
        Connection con;

        try {
            con = DriverManager.getConnection(jdbcDriver, jdbcLogin, jdbcPassword);
            return con;
        } catch (Exception e) {
            e.printStackTrace();
            return null;
        }
    }

    public ArrayList<User> getUsersList() {
        ArrayList<User> usersList = new ArrayList<User>();
        Connection connection = getConnection();

        String query = "SELECT * FROM `dane`";
        Statement st;
        ResultSet rs;

        try {
            st = connection.createStatement();
            rs = st.executeQuery(query);
            User user;
            while (rs.next()) {
                user = new User(rs.getInt("id"), rs.getString("username"), rs.getString("password"), rs.getString("firstname"), rs.getString("lastname"), rs.getString("email"), rs.getInt("age"), rs.getString("january_salary"), rs.getString("february_salary"), rs.getString("march_salary"), rs.getString("april_salary"), rs.getString("may_salary"), rs.getString("june_salary"), rs.getString("july_salary"), rs.getString("august_salary"), rs.getString("september_salary"), rs.getString("october_salary"), rs.getString("november_salary"), rs.getString("december_salary"));
                usersList.add(user);
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return usersList;
    }

    public void executeSQlQuery(String query, String message) {
        Connection con = getConnection();
        Statement st;
        try {
            st = con.createStatement();
            if ((st.executeUpdate(query)) == 1) {
                // Refreshing data in jTable
                DefaultTableModel model = (DefaultTableModel) jTable_Users.getModel();
                model.setRowCount(0);
                ShowUsersInJTable();

                JOptionPane.showMessageDialog(null, "Date " + message + " successfully");
            } else {
                JOptionPane.showMessageDialog(null, "Date NOT " + message);
            }

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    public void ShowUsersInJTable() {
        ArrayList<User> list = getUsersList();
        DefaultTableModel model = (DefaultTableModel) jTable_Users.getModel();
        Object[] row = new Object[19];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getUserName();
            row[2] = list.get(i).getPassword();
            row[3] = list.get(i).getFirstName();
            row[4] = list.get(i).getLastName();
            row[5] = list.get(i).getEMail();
            row[6] = list.get(i).getAge();
            row[7] = list.get(i).getJanuarySalary();
            row[8] = list.get(i).getFebruarySalary();
            row[9] = list.get(i).getMarchSalary();
            row[10] = list.get(i).getAprilSalary();
            row[11] = list.get(i).getMaySalary();
            row[12] = list.get(i).getJuneSalary();
            row[13] = list.get(i).getJulySalary();
            row[14] = list.get(i).getAugustSalary();
            row[15] = list.get(i).getSeptemberSalary();
            row[16] = list.get(i).getOctoberSalary();
            row[17] = list.get(i).getNovemberSalary();
            row[18] = list.get(i).getDecemberSalary();

            model.addRow(row);
        }
    }

    public void clearUsersInJTable() {
        DefaultTableModel model = (DefaultTableModel) jTable_Users.getModel();
        while (model.getRowCount() > 0) {
            for (int i = 0; i < model.getRowCount(); i++) {
                model.removeRow(i);
            }
        }
    }

    private void jLabel15MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MousePressed
        // reading coordination of pressed poin
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_jLabel15MousePressed

    private void jLabel15MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseDragged
        // moving form
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_jLabel15MouseDragged

    private void jLabel_IconifiedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_IconifiedMouseClicked
        // Iconified window
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel_IconifiedMouseClicked

    private void jLabel_ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ExitMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel_ExitMouseClicked

    private void jLabel_EditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EditMouseClicked
        String query = "UPDATE `dane` SET `username`='" + jTextField_UserName.getText() + "',`password`='" + jTextField_Password.getText() + "',`firstname`='" + jTextField_FirstName.getText() + "',`lastname`='" + jTextField_LastName.getText() + "',`email`='" + jTextField_Email.getText() + "',`age`=" + jTextField_Age.getText() + ",`january_salary`='" + jTextField_January.getText() + "',`february_salary`='" + jTextField_February.getText() + "',`march_salary`='" + jTextField_March.getText() + "',`april_salary`='" + jTextField_April.getText() + "',`may_salary`='" + jTextField_May.getText() + "',`june_salary`='" + jTextField_June.getText() + "',`july_salary`='" + jTextField_July.getText() + "',`august_salary`='" + jTextField_August.getText() + "',`september_salary`='" + jTextField_September.getText() + "',`october_salary`='" + jTextField_October.getText() + "',`november_salary`='" + jTextField_November.getText() + "',`december_salary`='" + jTextField_December.getText() + "' WHERE `id`=" + jTextField_ID.getText();
        executeSQlQuery(query, "Updated");
    }//GEN-LAST:event_jLabel_EditMouseClicked

    private void jLabel_RemoveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RemoveMouseClicked
        String query = "DELETE FROM `dane` WHERE id =" + jTextField_ID.getText();
        executeSQlQuery(query, "Deleted");
    }//GEN-LAST:event_jLabel_RemoveMouseClicked

    private void jLabel_AddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_AddMouseClicked
        String query = "INSERT INTO `dane`(`username`, `password`, `firstname`, `lastname`, `email`, `age`, `january_salary`, `february_salary`, `march_salary`, `april_salary`, `may_salary`, `june_salary`, `july_salary`, `august_salary`, `september_salary`, `october_salary`, `november_salary`, `december_salary`) VALUES ('" + jTextField_UserName.getText() + "','" + jTextField_Password.getText() + "','" + jTextField_FirstName.getText() + "','" + jTextField_LastName.getText() + "','" + jTextField_Email.getText() + "'," + jTextField_Age.getText() + ",'" + jTextField_January.getText() + "','" + jTextField_February.getText() + "','" + jTextField_March.getText() + "','" + jTextField_April.getText() + "','" + jTextField_May.getText() + "','" + jTextField_June.getText() + "','" + jTextField_July.getText() + "','" + jTextField_August.getText() + "','" + jTextField_September.getText() + "','" + jTextField_October.getText() + "','" + jTextField_November.getText() + "','" + jTextField_December.getText() + "')";
        executeSQlQuery(query, "Added");
    }//GEN-LAST:event_jLabel_AddMouseClicked

    private void jTable_UsersMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_UsersMousePressed
        // Show Users in TextFields
        int i = jTable_Users.getSelectedRow();
        TableModel model = jTable_Users.getModel();
        jTextField_ID.setText(model.getValueAt(i, 0).toString());
        jTextField_UserName.setText(model.getValueAt(i, 1).toString());
        jTextField_Password.setText(model.getValueAt(i, 2).toString());
        jTextField_FirstName.setText(model.getValueAt(i, 3).toString());
        jTextField_LastName.setText(model.getValueAt(i, 4).toString());
        jTextField_Email.setText(model.getValueAt(i, 5).toString());
        jTextField_Age.setText(model.getValueAt(i, 6).toString());
        jTextField_January.setText(model.getValueAt(i, 7).toString());
        jTextField_February.setText(model.getValueAt(i, 8).toString());
        jTextField_March.setText(model.getValueAt(i, 9).toString());
        jTextField_April.setText(model.getValueAt(i, 10).toString());
        jTextField_May.setText(model.getValueAt(i, 11).toString());
        jTextField_June.setText(model.getValueAt(i, 12).toString());
        jTextField_July.setText(model.getValueAt(i, 13).toString());
        jTextField_August.setText(model.getValueAt(i, 14).toString());
        jTextField_September.setText(model.getValueAt(i, 15).toString());
        jTextField_October.setText(model.getValueAt(i, 16).toString());
        jTextField_November.setText(model.getValueAt(i, 17).toString());
        jTextField_December.setText(model.getValueAt(i, 18).toString());
    }//GEN-LAST:event_jTable_UsersMousePressed

    private void jLabel_CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_CloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_jLabel_CloseMouseClicked

    private void jLabel_ManageUsersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ManageUsersMouseClicked
        resetColor(jPanel_Exit);
        setColor(jPanel_Manage);
        resetColor(jPanel_Login);
        resetColor(jPanel_Txt);
        resetColor(jPanel_Xls);
        resetColor(jPanel_Print);
        resetColor(jPanel_PDF);
        resetColor(jPanel_Email);
    }//GEN-LAST:event_jLabel_ManageUsersMouseClicked

    private void jLabel_LoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_LoginMouseClicked
        resetColor(jPanel_Exit);
        resetColor(jPanel_Manage);
        setColor(jPanel_Login);
        resetColor(jPanel_Txt);
        resetColor(jPanel_Xls);
        resetColor(jPanel_Print);
        resetColor(jPanel_PDF);
        resetColor(jPanel_Email);

        LoginForm lgf = new LoginForm();
        lgf.setVisible(true);
        lgf.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabel_LoginMouseClicked

    private void jLabel_TxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_TxtMouseClicked
        setColor(jPanel_Txt);
        resetColor(jPanel_Exit);
        resetColor(jPanel_Manage);
        resetColor(jPanel_Login);
        resetColor(jPanel_Xls);
        resetColor(jPanel_Print);
        resetColor(jPanel_PDF);
        resetColor(jPanel_Email);

        // Save raport as .txt file
        JFileChooser fs = new JFileChooser(new File("C:\\"));
        fs.setDialogTitle("Save a File");
        fs.setFileFilter(new FileTypeFilter(".txt", "Text File"));
        int result = fs.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File fi = fs.getSelectedFile();
            try {
                FileWriter fw = new FileWriter(fi.getPath() + ".txt");
                BufferedWriter bw = new BufferedWriter(fw);

                for (int i = 0; i < jTable_Users.getRowCount(); i++) {
                    for (int j = 0; j < jTable_Users.getColumnCount(); j++) {
                        bw.write(jTable_Users.getModel().getValueAt(i, j) + " | ");
                    }
                    bw.newLine();
                    bw.write("\n_________________________________________________________________________________________________________________________________________________________________\n");
                    bw.newLine();

                }
                bw.close();
                fw.close();
                JOptionPane.showMessageDialog(null, "Data exported to TXT successfully");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e.getMessage());
            }
        }
    }//GEN-LAST:event_jLabel_TxtMouseClicked

    private void jLabel_XlsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_XlsMouseClicked
        resetColor(jPanel_Txt);
        resetColor(jPanel_Exit);
        resetColor(jPanel_Manage);
        resetColor(jPanel_Login);
        setColor(jPanel_Xls);
        resetColor(jPanel_Print);
        resetColor(jPanel_PDF);
        resetColor(jPanel_Email);

        // Save raport as .xls file
        JFileChooser fs = new JFileChooser(new File("C:\\"));
        fs.setDialogTitle("Save a File");
        fs.setFileFilter(new FileTypeFilter(".xls", "Excel File"));
        int result = fs.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File fi = fs.getSelectedFile();
            try {
                HSSFWorkbook fWorkbook = new HSSFWorkbook();
                HSSFSheet fSheet = fWorkbook.createSheet("New Sheet");
                File file = new File(fi.getPath());
                HSSFCellStyle cellStyle = fWorkbook.createCellStyle();

                TableModel model = jTable_Users.getModel();

                for (int i = 0; i < model.getRowCount(); i++) {
                    HSSFRow fRow = fSheet.createRow((short) i);
                    for (int j = 0; j < model.getColumnCount(); j++) {
                        HSSFCell cell = fRow.createCell((short) j);
                        cell.setCellValue(model.getValueAt(i, j).toString());
                        cell.setCellStyle(cellStyle);
                    }
                }
                FileOutputStream fileOutputStream;
                fileOutputStream = new FileOutputStream(file + ".xls");
                BufferedOutputStream bos = new BufferedOutputStream(fileOutputStream);
                fWorkbook.write(bos);
                bos.close();
                fileOutputStream.close();
                JOptionPane.showMessageDialog(null, "Data exported to .xls successfully.");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jLabel_XlsMouseClicked

    private void jLabel_PrintMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_PrintMouseClicked
        resetColor(jPanel_Txt);
        resetColor(jPanel_Exit);
        resetColor(jPanel_Manage);
        resetColor(jPanel_Login);
        resetColor(jPanel_Xls);
        setColor(jPanel_Print);
        resetColor(jPanel_PDF);
        resetColor(jPanel_Email);

        MessageFormat header = new MessageFormat("Report print - Users list");
        MessageFormat footer = new MessageFormat("Page{0,number,integer}");
        try {
            jTable_Users.print(JTable.PrintMode.FIT_WIDTH, header, footer);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        }
    }//GEN-LAST:event_jLabel_PrintMouseClicked

    private void jLabel_PDFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_PDFMouseClicked
        resetColor(jPanel_Txt);
        resetColor(jPanel_Exit);
        resetColor(jPanel_Manage);
        resetColor(jPanel_Login);
        resetColor(jPanel_Xls);
        resetColor(jPanel_Print);
        setColor(jPanel_PDF);
        resetColor(jPanel_Email);

        JFileChooser fs = new JFileChooser(new File("C:\\"));
        fs.setDialogTitle("Save a File");
        fs.setFileFilter(new FileTypeFilter(".pdf", "PDF File"));
        int result = fs.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File fi = fs.getSelectedFile();

            try {
                Document doc = new Document(PageSize.A4.rotate(), 20, 20, 20, 20);
                PdfWriter.getInstance(doc, new FileOutputStream(fi.getPath() + ".pdf"));
                doc.open();
                doc.add(new Paragraph(new Date().toString()));
                doc.add(new Paragraph("."));
                PdfPTable table = new PdfPTable(jTable_Users.getColumnCount());
                table.setWidthPercentage(100);
                System.out.println(jTable_Users.getColumnCount());

                //  Table headers
                for (int k = 0; k < jTable_Users.getColumnCount(); k++) {
                    table.addCell(jTable_Users.getColumnName(k).toString());
                }

                //  Data from table
                for (int i = 0; i < jTable_Users.getRowCount(); i++) {
                    for (int j = 0; j < jTable_Users.getColumnCount(); j++) {
                        table.addCell(jTable_Users.getModel().getValueAt(i, j).toString());
                    }
                }
                doc.add(table);
                doc.close();
                JOptionPane.showMessageDialog(null, "Data exported to PDF successfully");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_jLabel_PDFMouseClicked

    private void jLabel_RefreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_RefreshMouseClicked
        clearUsersInJTable();
        ShowUsersInJTable();
    }//GEN-LAST:event_jLabel_RefreshMouseClicked

    private void jLabel_EmailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_EmailMouseClicked
        resetColor(jPanel_Txt);
        resetColor(jPanel_Exit);
        resetColor(jPanel_Manage);
        resetColor(jPanel_Login);
        resetColor(jPanel_Xls);
        resetColor(jPanel_Print);
        resetColor(jPanel_PDF);
        setColor(jPanel_Email);

        Email efm = new Email(jTextField_Email.getText());
        efm.setVisible(true);
        efm.pack();
        efm.setLocationRelativeTo(null);
    }//GEN-LAST:event_jLabel_EmailMouseClicked

    private void jLabel_SearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_SearchMouseClicked
        if (jTextField_ID.hasFocus()) {
            searchUserById(Integer.parseInt(jTextField_ID.getText()));
        } else if (jTextField_UserName.hasFocus()) {
            searchUserByUserName(jTextField_UserName.getText());
        } else if (jTextField_FirstName.hasFocus()) {
            searchUserByFirstName(jTextField_FirstName.getText());
        } else if (jTextField_LastName.hasFocus()) {
            searchUserByLastName(jTextField_LastName.getText());
        } else if (jTextField_Email.hasFocus()) {
            searchUserByEmail(jTextField_Email.getText());
        } else if (jTextField_Age.hasFocus()) {
            searchUserByAge(Integer.parseInt(jTextField_Age.getText()));
        } else {
            System.out.println("Something is wrong with search Focus");
        }
    }//GEN-LAST:event_jLabel_SearchMouseClicked

    private void jLabel_ClearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel_ClearMouseClicked
        jTextField_ID.setText(null);
        jTextField_UserName.setText(null);
        jTextField_Password.setText(null);
        jTextField_FirstName.setText(null);
        jTextField_LastName.setText(null);
        jTextField_Email.setText(null);
        jTextField_Age.setText(null);

        jTextField_January.setText(null);
        jTextField_February.setText(null);
        jTextField_March.setText(null);
        jTextField_April.setText(null);
        jTextField_May.setText(null);
        jTextField_June.setText(null);
        jTextField_July.setText(null);
        jTextField_August.setText(null);
        jTextField_September.setText(null);
        jTextField_October.setText(null);
        jTextField_November.setText(null);
        jTextField_December.setText(null);
    }//GEN-LAST:event_jLabel_ClearMouseClicked

    private void searchUserById(int id) {
        clearUsersInJTable();

        ArrayList<User> list = getUsersList();
        DefaultTableModel model = (DefaultTableModel) jTable_Users.getModel();
        Object[] row = new Object[19];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getUserName();
            row[2] = list.get(i).getPassword();
            row[3] = list.get(i).getFirstName();
            row[4] = list.get(i).getLastName();
            row[5] = list.get(i).getEMail();
            row[6] = list.get(i).getAge();
            row[7] = list.get(i).getJanuarySalary();
            row[8] = list.get(i).getFebruarySalary();
            row[9] = list.get(i).getMarchSalary();
            row[10] = list.get(i).getAprilSalary();
            row[11] = list.get(i).getMaySalary();
            row[12] = list.get(i).getJuneSalary();
            row[13] = list.get(i).getJulySalary();
            row[14] = list.get(i).getAugustSalary();
            row[15] = list.get(i).getSeptemberSalary();
            row[16] = list.get(i).getOctoberSalary();
            row[17] = list.get(i).getNovemberSalary();
            row[18] = list.get(i).getDecemberSalary();

            if (row[0].equals(id)) {
                model.addRow(row);
            }
        }
    }

    private void searchUserByUserName(String userName) {
        clearUsersInJTable();

        ArrayList<User> list = getUsersList();
        DefaultTableModel model = (DefaultTableModel) jTable_Users.getModel();
        Object[] row = new Object[19];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getUserName();
            row[2] = list.get(i).getPassword();
            row[3] = list.get(i).getFirstName();
            row[4] = list.get(i).getLastName();
            row[5] = list.get(i).getEMail();
            row[6] = list.get(i).getAge();
            row[7] = list.get(i).getJanuarySalary();
            row[8] = list.get(i).getFebruarySalary();
            row[9] = list.get(i).getMarchSalary();
            row[10] = list.get(i).getAprilSalary();
            row[11] = list.get(i).getMaySalary();
            row[12] = list.get(i).getJuneSalary();
            row[13] = list.get(i).getJulySalary();
            row[14] = list.get(i).getAugustSalary();
            row[15] = list.get(i).getSeptemberSalary();
            row[16] = list.get(i).getOctoberSalary();
            row[17] = list.get(i).getNovemberSalary();
            row[18] = list.get(i).getDecemberSalary();

            if (row[1].equals(userName)) {
                model.addRow(row);
            }
        }
    }

    private void searchUserByFirstName(String firstName) {
        clearUsersInJTable();

        ArrayList<User> list = getUsersList();
        DefaultTableModel model = (DefaultTableModel) jTable_Users.getModel();
        Object[] row = new Object[19];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getUserName();
            row[2] = list.get(i).getPassword();
            row[3] = list.get(i).getFirstName();
            row[4] = list.get(i).getLastName();
            row[5] = list.get(i).getEMail();
            row[6] = list.get(i).getAge();
            row[7] = list.get(i).getJanuarySalary();
            row[8] = list.get(i).getFebruarySalary();
            row[9] = list.get(i).getMarchSalary();
            row[10] = list.get(i).getAprilSalary();
            row[11] = list.get(i).getMaySalary();
            row[12] = list.get(i).getJuneSalary();
            row[13] = list.get(i).getJulySalary();
            row[14] = list.get(i).getAugustSalary();
            row[15] = list.get(i).getSeptemberSalary();
            row[16] = list.get(i).getOctoberSalary();
            row[17] = list.get(i).getNovemberSalary();
            row[18] = list.get(i).getDecemberSalary();

            if (row[3].equals(firstName)) {
                model.addRow(row);
            }
        }
    }

    private void searchUserByLastName(String lastName) {
        clearUsersInJTable();

        ArrayList<User> list = getUsersList();
        DefaultTableModel model = (DefaultTableModel) jTable_Users.getModel();
        Object[] row = new Object[19];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getUserName();
            row[2] = list.get(i).getPassword();
            row[3] = list.get(i).getFirstName();
            row[4] = list.get(i).getLastName();
            row[5] = list.get(i).getEMail();
            row[6] = list.get(i).getAge();
            row[7] = list.get(i).getJanuarySalary();
            row[8] = list.get(i).getFebruarySalary();
            row[9] = list.get(i).getMarchSalary();
            row[10] = list.get(i).getAprilSalary();
            row[11] = list.get(i).getMaySalary();
            row[12] = list.get(i).getJuneSalary();
            row[13] = list.get(i).getJulySalary();
            row[14] = list.get(i).getAugustSalary();
            row[15] = list.get(i).getSeptemberSalary();
            row[16] = list.get(i).getOctoberSalary();
            row[17] = list.get(i).getNovemberSalary();
            row[18] = list.get(i).getDecemberSalary();

            if (row[4].equals(lastName)) {
                model.addRow(row);
            }
        }
    }

    private void searchUserByEmail(String email) {
        clearUsersInJTable();

        ArrayList<User> list = getUsersList();
        DefaultTableModel model = (DefaultTableModel) jTable_Users.getModel();
        Object[] row = new Object[19];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getUserName();
            row[2] = list.get(i).getPassword();
            row[3] = list.get(i).getFirstName();
            row[4] = list.get(i).getLastName();
            row[5] = list.get(i).getEMail();
            row[6] = list.get(i).getAge();
            row[7] = list.get(i).getJanuarySalary();
            row[8] = list.get(i).getFebruarySalary();
            row[9] = list.get(i).getMarchSalary();
            row[10] = list.get(i).getAprilSalary();
            row[11] = list.get(i).getMaySalary();
            row[12] = list.get(i).getJuneSalary();
            row[13] = list.get(i).getJulySalary();
            row[14] = list.get(i).getAugustSalary();
            row[15] = list.get(i).getSeptemberSalary();
            row[16] = list.get(i).getOctoberSalary();
            row[17] = list.get(i).getNovemberSalary();
            row[18] = list.get(i).getDecemberSalary();

            if (row[5].equals(email)) {
                model.addRow(row);
            }
        }
    }

    private void searchUserByAge(int age) {
        clearUsersInJTable();

        ArrayList<User> list = getUsersList();
        DefaultTableModel model = (DefaultTableModel) jTable_Users.getModel();
        Object[] row = new Object[19];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getId();
            row[1] = list.get(i).getUserName();
            row[2] = list.get(i).getPassword();
            row[3] = list.get(i).getFirstName();
            row[4] = list.get(i).getLastName();
            row[5] = list.get(i).getEMail();
            row[6] = list.get(i).getAge();
            row[7] = list.get(i).getJanuarySalary();
            row[8] = list.get(i).getFebruarySalary();
            row[9] = list.get(i).getMarchSalary();
            row[10] = list.get(i).getAprilSalary();
            row[11] = list.get(i).getMaySalary();
            row[12] = list.get(i).getJuneSalary();
            row[13] = list.get(i).getJulySalary();
            row[14] = list.get(i).getAugustSalary();
            row[15] = list.get(i).getSeptemberSalary();
            row[16] = list.get(i).getOctoberSalary();
            row[17] = list.get(i).getNovemberSalary();
            row[18] = list.get(i).getDecemberSalary();

            if (row[6].equals(age)) {
                model.addRow(row);
            }
        }
    }

    void setColor(JPanel panel) {
        panel.setBackground(new Color(12, 115, 115));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(31, 174, 174));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel_Add;
    private javax.swing.JLabel jLabel_Clear;
    private javax.swing.JLabel jLabel_Close;
    private javax.swing.JLabel jLabel_Edit;
    private javax.swing.JLabel jLabel_Email;
    private javax.swing.JLabel jLabel_Exit;
    private javax.swing.JLabel jLabel_Iconified;
    private javax.swing.JLabel jLabel_Login;
    private javax.swing.JLabel jLabel_ManageUsers;
    private javax.swing.JLabel jLabel_PDF;
    private javax.swing.JLabel jLabel_Print;
    private javax.swing.JLabel jLabel_Refresh;
    private javax.swing.JLabel jLabel_Remove;
    private javax.swing.JLabel jLabel_Search;
    private javax.swing.JLabel jLabel_Txt;
    private javax.swing.JLabel jLabel_Xls;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel_Email;
    private javax.swing.JPanel jPanel_Exit;
    private javax.swing.JPanel jPanel_Login;
    private javax.swing.JPanel jPanel_Manage;
    private javax.swing.JPanel jPanel_PDF;
    private javax.swing.JPanel jPanel_Print;
    private javax.swing.JPanel jPanel_Txt;
    private javax.swing.JPanel jPanel_Xls;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_Users;
    private javax.swing.JTextField jTextField_Age;
    private javax.swing.JTextField jTextField_April;
    private javax.swing.JTextField jTextField_August;
    private javax.swing.JTextField jTextField_December;
    private javax.swing.JTextField jTextField_Email;
    private javax.swing.JTextField jTextField_February;
    private javax.swing.JTextField jTextField_FirstName;
    private javax.swing.JTextField jTextField_ID;
    private javax.swing.JTextField jTextField_January;
    private javax.swing.JTextField jTextField_July;
    private javax.swing.JTextField jTextField_June;
    private javax.swing.JTextField jTextField_LastName;
    private javax.swing.JTextField jTextField_March;
    private javax.swing.JTextField jTextField_May;
    private javax.swing.JTextField jTextField_November;
    private javax.swing.JTextField jTextField_October;
    private javax.swing.JTextField jTextField_Password;
    private javax.swing.JTextField jTextField_September;
    private javax.swing.JTextField jTextField_UserName;
    // End of variables declaration//GEN-END:variables
}
